### ISSUE TITLE
minOccurs and maxOccurs cannot be attributes in <element>

### ISSUE THREAD

**Issue by GoogleCodeExporter** [robinzt/dtd2xsdjava#1]
```
The converter generates "minOccurs" and "maxOccurs"  attributes on <element>. 
When attempting to validate this with JAXB, it fails. Those two attributes are 
not allowed on <element> in XSDs.
```

Original issue reported on code.google.com by `mar...@naskovski.info` on 15 Feb 2013 at 4:23

**Comment by robinzt** [comment]
https://www.w3schools.com/xml/schema_complex_indicators.asp

The <maxOccurs> indicator specifies the maximum number of times an element can occur:
`<xs:element name="person">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="full_name" type="xs:string"/>
      <xs:element name="child_name" type="xs:string" maxOccurs="10"/>
    </xs:sequence>
  </xs:complexType>
</xs:element> `

The <minOccurs> indicator specifies the minimum number of times an element can occur:
`
<xs:element name="person">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="full_name" type="xs:string"/>
      <xs:element name="child_name" type="xs:string"
      maxOccurs="10" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:element> `
